name: Build NES Delta Dash

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install cc65
      run: |
        sudo apt-get update
        sudo apt-get install -y cc65

    - name: Build NES ROM
      run: |
        make clean
        make all
      working-directory: .

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v3
      with:
        name: delta-dash-nes
        path: delta_dash.nes
        
